"""create all tables

Revision ID: a36bf13e4d8f
Revises: 
Create Date: 2020-01-05 18:36:52.462698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36bf13e4d8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroomname', sa.String(length=128), nullable=True),
    sa.Column('classroomnumber', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_classroomname'), 'classrooms', ['classroomname'], unique=True)
    op.create_index(op.f('ix_classrooms_classroomnumber'), 'classrooms', ['classroomnumber'], unique=True)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teachersname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_teachersname'), 'teacher', ['teachersname'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('class_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teachersname', sa.String(length=128), nullable=True),
    sa.Column('classroom', sa.String(length=128), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_session_classroom'), 'class_session', ['classroom'], unique=False)
    op.create_index(op.f('ix_class_session_teachersname'), 'class_session', ['teachersname'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_class_session_teachersname'), table_name='class_session')
    op.drop_index(op.f('ix_class_session_classroom'), table_name='class_session')
    op.drop_table('class_session')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_teacher_teachersname'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_classrooms_classroomnumber'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_classroomname'), table_name='classrooms')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
