"""create azure-sql-db

Revision ID: e1c266258ba0
Revises: 
Create Date: 2020-01-07 21:15:21.819696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c266258ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroomname', sa.String(length=128), nullable=True),
    sa.Column('classroomnumber', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Classrooms_classroomname'), 'Classrooms', ['classroomname'], unique=True)
    op.create_index(op.f('ix_Classrooms_classroomnumber'), 'Classrooms', ['classroomnumber'], unique=True)
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teachersname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Teacher_teachersname'), 'Teacher', ['teachersname'], unique=True)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('ClassSessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teachersname', sa.String(length=128), nullable=True),
    sa.Column('classroom', sa.String(length=128), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['Classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ClassSessions_classroom'), 'ClassSessions', ['classroom'], unique=False)
    op.create_index(op.f('ix_ClassSessions_teachersname'), 'ClassSessions', ['teachersname'], unique=False)
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Post_timestamp'), 'Post', ['timestamp'], unique=False)
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('PersonID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LastName', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FirstName', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Address', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('City', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_Post_timestamp'), table_name='Post')
    op.drop_table('Post')
    op.drop_index(op.f('ix_ClassSessions_teachersname'), table_name='ClassSessions')
    op.drop_index(op.f('ix_ClassSessions_classroom'), table_name='ClassSessions')
    op.drop_table('ClassSessions')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Teacher_teachersname'), table_name='Teacher')
    op.drop_table('Teacher')
    op.drop_index(op.f('ix_Classrooms_classroomnumber'), table_name='Classrooms')
    op.drop_index(op.f('ix_Classrooms_classroomname'), table_name='Classrooms')
    op.drop_table('Classrooms')
    # ### end Alembic commands ###
